"""'增加todos表'

Revision ID: 67614dc9161f
Revises: 0004ceb5d124
Create Date: 2017-01-20 22:49:16.023753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67614dc9161f'
down_revision = '0004ceb5d124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'password')
    # ### end Alembic commands ###
